---
##############################
# StaffList Created by NightmareCybers! D
# Your using version 6.9
# Check for updates regularly!
##############################


#Add staff below, You may leave some blank.
staff1 xFlare is awesome!
staff2 Example
staff3 Example
staff4 Example
staff5 Example
staff6 Example
staff7 Example
staff8 Example
staff9 Example
staff10 Example
#Please do not add more staff slots!
#It may corrupt the config file!
...